[package]
name = "dddl"
version = "0.1.0"
authors = ["kena0ki <ken3574.25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.7.0"
